[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.102"
tokio = { version = "1.50.0", features = ["macros", "rt-multi-thread"] }
lambda_runtime = "1"
lambda_http = "1"
tracing-subscriber = "0.3.23"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
prost = "0.13"
tonic = { version = "0.13", features = ["transport", "prost"] }
tonic-web = "0.13"
tower = "0.5"
tower-http = { version = "0.6", features = ["cors"] }
protocol_macro = { path = "src/protocol-macro" }
snap = "1"
aws-config = "1"
aws-credential-types = "1"
aws_lambda_events = { version = "1", default-features = false, features = ["sqs", "cognito"] }
aws-sdk-cognitoidentityprovider = "1"
aws-sdk-dynamodb = "1"
serde_dynamo = { version = "4", features = ["aws-sdk-dynamodb+1"] }
schemars = "1.2"
chrono = { version = "0.4", features = ["serde"] }
wiremock = "0.6.5"
base64 = "0.21"

[build-dependencies]
prost-build = "0.13"
prost-types = "0.13"
prost = "0.13"
tonic-build = "0.13"

[dev-dependencies]
expectorate = "1"

[[bin]]
name = "password-policy"
path = "src/password-policy.rs"

[[bin]]
name = "cognito-handler"
path = "src/cognito-handler.rs"

[[bin]]
name = "message-handler"
path = "src/message-handler.rs"

[[bin]]
name = "user-profile"
path = "src/user-profile.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[profile.release]
codegen-units = 1 # Reduce binary size by compiling all code in one unit
lto = "fat" # Enable best link-time optimization to reduce binary size
