name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  # Builds the backend if it wasn't part of the cache
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Calculate Hash
        id: hash
        run: echo "source_hash=${{ hashFiles('backend/**') }}" >> $GITHUB_OUTPUT
      - name: Restore Backend Build
        id: cache
        uses: actions/cache@v5
        with:
          path: backend-artifacts/
          key: backend-${{ steps.hash.outputs.source_hash }}
      - uses: Swatinem/rust-cache@v2
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          workspaces: ./backend
          cache-on-failure: true
      - name: Install Protoc
        if: steps.cache.outputs.cache-hit != 'true'
        uses: arduino/setup-protoc@v3
      - name: Cross compile Backend and package artifacts
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: backend
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          rustup target add aarch64-unknown-linux-gnu

          cargo build --release --target aarch64-unknown-linux-gnu

          mkdir -p ../backend-artifacts
          for file in target/aarch64-unknown-linux-gnu/release/*; do
            if [ -f "$file" ]; then
              cp "$file" ../backend-artifacts/
            fi
          done
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
          CARGO_TERM_COLOR: always
      - name: Upload Backend Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: backend-binaries
          path: backend-artifacts/
          retention-days: 1

  # Builds the frontend if it wasn't part of the cache
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Calculate Hash
        id: hash
        run: echo "source_hash=${{ hashFiles('frontend/**') }}" >> $GITHUB_OUTPUT
      - name: Restore Frontend Build
        id: cache
        uses: actions/cache@v5
        with:
          path: frontend/build/
          key: frontend-${{ steps.hash.outputs.source_hash }}
      - name: Setup Node.js
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install Protoc
        if: steps.cache.outputs.cache-hit != 'true'
        uses: arduino/setup-protoc@v3
      - name: Build Frontend
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./frontend
        run: |
          npm ci
          npm run build
      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v7
        with:
          name: frontend-build
          path: frontend/build/
          retention-days: 1

  deploy-staging:
    needs: [build-backend, build-frontend]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging
      domain: ${{ vars.DOMAIN_STAGING }}
      awsRoleArn: ${{ vars.AWS_ROLE_ARN_STAGING }}
      certificateArn: ${{ vars.CERTIFICATE_ARN_STAGING }}

  deploy-production:
    needs: [deploy-staging]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      domain: ${{ vars.DOMAIN_PRODUCTION }}
      awsRoleArn: ${{ vars.AWS_ROLE_ARN_PRODUCTION }}
      certificateArn: ${{ vars.CERTIFICATE_ARN_PRODUCTION }}
